USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/zte/elden/BoardConfigVendor.mk

# General
TARGET_BOOTLOADER_BOARD_NAME := elden
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm8960
TARGET_BOARD_PLATFORM_FPU := neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_ARCH_VARIANT := armv7-a-neon

TARGET_USE_KRAIT_BIONIC_OPTIMIZATION := true
TARGET_USE_KRAIT_PLD_SET := true
TARGET_KRAIT_BIONIC_PLDOFFS := 10
TARGET_KRAIT_BIONIC_PLDTHRESH := 10
TARGET_KRAIT_BIONIC_BBTHRESH := 64
TARGET_KRAIT_BIONIC_PLDSIZE := 64

ARCH_ARM_HAVE_TLS_REGISTER := true
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_ARMV7A := true

BOARD_USES_ADRENO_200 := true
BOARD_USES_HWCOMPOSER := true
BOARD_USES_GENLOCK := true
BOARD_NEEDS_MEMORYHEAPPMEM := true
BOARD_CDMA_NETWORK := true

TARGET_NO_HW_VSYNC := true
TARGET_USES_SF_BYPASS := true
TARGET_USES_OVERLAY := true
TARGET_FORCE_CPU_UPLOAD := true

BOARD_USES_QCOM_HARDWARE := true
QCOM_TARGET_PRODUCT := msm8960
BOARD_USE_QCOM_PMEM := true
TARGET_USES_QCOM_LPA := true
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true

# Flags
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp -march=armv7-a
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp -march=armv7-a

COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE -DWITH_QCOM_LPA
COMMON_GLOBAL_CFLAGS += -DQCOM_NO_SECURE_PLAYBACK -DQCOM_ROTATOR_KERNEL_FORMATS
COMMON_GLOBAL_CFLAGS += -DQCOM_ICS_COMPAT -DQCOM_ACDB_ENABLED
COMMON_GLOBAL_CFLAGS += -DUSE_QMI -DFORCE_CPU_UPLOAD -DBINDER_COMPAT
COMMON_GLOBAL_CFLAGS += -DZTE_MSM8960 -DNEED_UMS_ENABLE -DENABLE_UMS_WITH_DATAMEDIA

# Audio
BOARD_USES_ALSA_AUDIO := true
TARGET_USES_ION_AUDIO := true
BOARD_USES_SRS_TRUEMEDIA := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true

# Display/Video
BOARD_EGL_CFG := device/zte/elden/prebuilts/lib/egl/egl.cfg
#BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
BOARD_USE_SKIA_LCDTEXT := true
TARGET_BOARD_PLATFORM_GPU := qcom-adreno225
TARGET_QCOM_HDMI_OUT := true
TARGET_HARDWARE_3D := true
USE_OPENGL_RENDERER := true
TARGET_USES_ION := true
TARGET_USES_C2D_COMPOSITION := true

# FM Radio
#BOARD_HAVE_FM_RADIO := true
#BOARD_GLOBAL_CFAGS += -DHAVE_FM_RADIO

# GPS
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := default

# Lights
TARGET_PROVIDES_LIBLIGHT := true

# JIT / Optimizations
WITH_DEXPREOPT := true
JS_ENGINE := v8

# Webkit
ENABLE_WEBGL := true

# Wifi

# Kernel
BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom user_debug=31 loglevel=7 kgsl.mmutype=gpummu
BOARD_KERNEL_BASE := 0x80200000
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x01300000
BOARD_KERNEL_PAGESIZE := 2048

TARGET_PREBUILT_KERNEL := device/zte/elden/kernel

TARGET_KERNEL_CUSTOM_TOOLCHAIN := arm-eabi-4.4.3

#TARGET_KERNEL_CONFIG := msm8960-elden_defconfig

#TARGET_SPECIFIC_HEADER_PATH += device/zte/elden/include

TARGET_PROVIDES_INIT_RC := true

# Parttions
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 480018432
BOARD_CACHEIMAGE_PARTITION_SIZE := 318767104
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2793406464
BOARD_PERSISTIMAGE_PARTITION_SIZE := 25165824
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_USES_MMCUTILS := true
BOARD_HAS_SDCARD_INTERNAL := true
#BOARD_SDCARD_DEVICE_PRIMARY := /dev/block/vold/179:32

# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_RECOVERY_HANDLES_MOUNT := true
BOARD_HAS_DOWNLOAD_MODE := true
TARGET_PREBUILT_RECOVERY_KERNEL := device/zte/elden/recovery/kernel
BOARD_CUSTOM_GRAPHICS := ../../../device/zte/elden/recovery/graphics.c

# USB
BOARD_CUSTOM_USB_CONTROLLER := ../../device/zte/elden/UsbController.cpp
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
BOARD_UMS_LUNFILE := "/sys/devices/platform/msm_hsusb/gadget/lun0/file"
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/msm_hsusb/gadget/lun0/file"

#TARGET_PROVIDES_RELEASETOOLS := true
#TARGET_RELEASETOOL_OTA_FROM_TARGET_SCRIPT :=
